imports = ["common", "filesystems/btrfs", "laptop_temp", "virtualbox"]

paru = [
  "antimicrox",
  "batsignal",
  "bindfs",
  "bluez-utils",
  "cups",
  "evremap-git",
  "foliate",
  "intel-ucode",
  "intel-media-driver",
  "gst-plugin-va",
  "lib32-vulkan-intel",
  "lib32-opencl-mesa",
  "limine",
  "limine-snapper-sync",
  "limine-mkinitcpio-hook",
  "linux-firmware-intel",
  "linux-firmware-realtek",
  "linux-firmware-other",
  "linux-firmware-whence",
  "opencl-mesa",
  "snap-pac",
  "sshfs",
  "usbguard",
  "wezterm",
  "wireless_tools",
  "vulkan-intel",
  "vpl-gpu-rt",
]

service = [
  "bluetooth",
  "cups",
  "cups.path",
  "cups.socket",
  "evremap",
  "macchanger@wlp2s0",
  "usbguard",
]
