imports = [
  # "arch_wiki",
  "activitywatch",
  "communication",
  "development",
  "filesystems",
  "games",
  "gnome",
  "hacking",
  "nvim",
  "profiling",
  "rust",
  "sandboxing",
  "school",
  "syncthing",
  "system",
  "temp",
  "terminal",
  "wayland",
  "zig",
]

paru = [
  "anymex-bin",
  "blender",
  "davfs2",
  "firefox",
  "keepassxc",
  "localsend",
  "macchanger",
  "obsidian",
  "pandoc-bin",
  "paruz",
  "smartmontools",
  "spotify",
  "svgcleaner",
  "torbrowser-launcher",
  "vlc",
  "vlc-plugin-ffmpeg",
  "warp",
  "zotero",
]

files = [
  "/etc/rustic",
  "/etc/locale.gen",
  "/etc/ssh/sshd_config",
  "/{home}/.config/environment.d/10-ssh-agent.conf",
  "/{home}/Documents",
  "/{home}/KeePassXcDatabase",
  "/{home}/Obsidian",
  "/{home}/spotility",
  "/{home}/user-files",
  "/{home}/server-files",
  "/{home}/.config/browser",
  "/{home}/.config/pixel8a",
  "/{home}/.config/spicetify",
]
