paru = ["git", "jq", "libgit2", "namcap", "neovim", "zed"]

cargo = [
  "add-license",
  "git-cliff",
  "hyperfine",
  "jj-cli",
  "mask",
  "tokei",
  "typos-cli",
]

files = [
  "/{home}/Code",
  "{hostname}/{home}/.radicle",
  "/{home}/.config/nvim",
  "/{home}/.config/systemd",
  "/{home}/.config/jj/config.toml",
  "/{home}/.config/zed",
  "/{home}/.gitconfig",
]

service-user = "ssh-agent"
