paru = [
  "dconf-editor",
  "evince",
  "extension-manager",
  "file-roller",
  "gdm",
  "gnome-backgrounds",
  "gnome-calculator",
  "gnome-characters",
  "gnome-clocks",
  "gnome-color-manager",
  "gnome-console",
  "gnome-control-center",
  "gnome-disk-utility",
  "gnome-logs",
  "gnome-menus",
  "gnome-power-manager",
  "gnome-shell",
  "gnome-shell-extensions",
  "gnome-system-monitor",
  "gnome-tweaks",
  "gnome-usage",
  "gnumeric",
  "loupe",
  "nautilus",
  "sushi",
]

service = "gdm"

files = [
  "{hostname}/{home}/.config/dconf",
  "/{home}/.local/share/authenticator",
  "/{home}/.local/share/gnome-shell/extensions",
]
