paru = [
  "activitywatch-bin",
  "aw-awatcher",
  "anyrun",
  "brightnessctl",
  "cliphist",
  "eww-git",
  "hyprpicker",
  "mako",
  "niri",
  "swaylock",
  "swww",
  "xwayland-satellite",
]

files = [
  "/{home}/ActivityWatchSync",
  "/{home}/Wallpapers",
  "/{home}/.config/anyrun",
  "/{home}/.config/eww",
  "/{home}/.config/niri",
  "/etc/systemd/system/clear_clipboard_history.service",
]
service = "clear_clipboard_history"
service-user = ["aw-server-rust", "aw-awatcher", "aw-sync"]
